services:
  db:
    image: postgres:15-alpine
    container_name: django-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./env_file.txt
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: django-backend
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8001 --reload --reload-include '*.py'
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    env_file:
      - ./env_file.txt
    depends_on:
      - db